name: Format JSON
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format JSON
        run: |
          jq . data.json > formatted.json
          mv formatted.json data.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Auto-format JSON" || exit 0
          git push
